url: "https://nixsupport.github.io"
baseurl: "/karanbrar/"

# Site settings
title: Karan Brar
email: contact@karanbrar.ca
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Balkaran Brar
  pic: 1
  position: Consultant and Trainer
  social:
    - title: twitter
      url: karanb81
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
collections:
  articles:
    output: true